Footer
dev-KPI/pokemons-web pull request #4
Opened 2022-10-27 23:54 UTC by panjuksergy

Here u can find fixed Header with my designed footer

2022-11-08 21:38 UTC, panjuksergy commented on src/basic.css
> +  margin-top: 30px;
Idk how to make in another way. I think this **_hardcode_** perfect

2022-11-08 21:47 UTC, panjuksergy commented
@DemianParkhomenko 
Could u pls check this and make review to marge this pl !

2022-11-12 17:21 UTC, DemianParkhomenko requested changes
Adaptive layout for phones is broken: 
![image](https://user-images.githubusercontent.com/95881717/201486256-6fe17e3b-160a-430b-9ffd-1d65ded37441.png)
![image](https://user-images.githubusercontent.com/95881717/201486299-b0da2fd7-129a-49fc-827b-705ee4c36539.png)

2022-11-12 17:21 UTC, DemianParkhomenko commented on src/basic-adaptation.css
> +    width: 40px;
Suggest:
```
   --size: 40px
    width: var(--size);
    height: var(--size);
    line-height: var(--size); 
```

2022-11-14 18:49 UTC, panjuksergy commented on src/Pages/home.html
> +          <span class="menu"> <span class="hamburger"></span> </span>
burger = ham + burger bro))

2022-11-14 18:52 UTC, panjuksergy commented on src/basic-adaptation.css
> +@media screen and (max-width: 544px) {
I changed the resolution while the site worked fine. When something went wrong, I created a new breakpoint

2022-11-14 18:52 UTC, panjuksergy commented on src/basic.css
> +  background: #55acee;
Ok

2023-01-03 13:03 UTC, merged